# Autogenerated wrapper script for patchutils_jll for powerpc64le-linux-gnu
export combinediff, dehtmldiff, editdiff, espdiff, filterdiff, flipdiff, gitdiff, grepdiff, interdiff, lsdiff, recountdiff, rediff, splitdiff, svndiff, unwrapdiff

JLLWrappers.@generate_wrapper_header("patchutils")
JLLWrappers.@declare_executable_product(combinediff)
JLLWrappers.@declare_executable_product(dehtmldiff)
JLLWrappers.@declare_executable_product(editdiff)
JLLWrappers.@declare_executable_product(espdiff)
JLLWrappers.@declare_executable_product(filterdiff)
JLLWrappers.@declare_executable_product(flipdiff)
JLLWrappers.@declare_executable_product(gitdiff)
JLLWrappers.@declare_executable_product(grepdiff)
JLLWrappers.@declare_executable_product(interdiff)
JLLWrappers.@declare_executable_product(lsdiff)
JLLWrappers.@declare_executable_product(recountdiff)
JLLWrappers.@declare_executable_product(rediff)
JLLWrappers.@declare_executable_product(splitdiff)
JLLWrappers.@declare_executable_product(svndiff)
JLLWrappers.@declare_executable_product(unwrapdiff)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        combinediff,
        "bin/combinediff",
    )

    JLLWrappers.@init_executable_product(
        dehtmldiff,
        "bin/dehtmldiff",
    )

    JLLWrappers.@init_executable_product(
        editdiff,
        "bin/editdiff",
    )

    JLLWrappers.@init_executable_product(
        espdiff,
        "bin/espdiff",
    )

    JLLWrappers.@init_executable_product(
        filterdiff,
        "bin/filterdiff",
    )

    JLLWrappers.@init_executable_product(
        flipdiff,
        "bin/flipdiff",
    )

    JLLWrappers.@init_executable_product(
        gitdiff,
        "bin/gitdiff",
    )

    JLLWrappers.@init_executable_product(
        grepdiff,
        "bin/grepdiff",
    )

    JLLWrappers.@init_executable_product(
        interdiff,
        "bin/interdiff",
    )

    JLLWrappers.@init_executable_product(
        lsdiff,
        "bin/lsdiff",
    )

    JLLWrappers.@init_executable_product(
        recountdiff,
        "bin/recountdiff",
    )

    JLLWrappers.@init_executable_product(
        rediff,
        "bin/rediff",
    )

    JLLWrappers.@init_executable_product(
        splitdiff,
        "bin/splitdiff",
    )

    JLLWrappers.@init_executable_product(
        svndiff,
        "bin/svndiff",
    )

    JLLWrappers.@init_executable_product(
        unwrapdiff,
        "bin/unwrapdiff",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
